# Generated by Django 3.1.1 on 2021-05-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDrink', models.CharField(max_length=255)),
                ('strDrink', models.CharField(max_length=255)),
                ('strDrinkAlternate', models.CharField(max_length=255)),
                ('strTags', models.CharField(max_length=255)),
                ('strVideo', models.CharField(max_length=255)),
                ('strIBA', models.CharField(max_length=255)),
                ('strAlcoholic', models.CharField(max_length=255)),
                ('strGlass', models.CharField(max_length=255)),
                ('strInstructions', models.CharField(max_length=255)),
                ('strInstructionsES', models.CharField(max_length=255)),
                ('strInstructionsDE', models.CharField(max_length=255)),
                ('strInstructionsFR', models.CharField(max_length=255)),
                ('strInstructionsIT', models.CharField(max_length=255)),
                ('strInstructionsZH_HANS', models.CharField(max_length=255)),
                ('strInstructionsZH_HANT', models.CharField(max_length=255)),
                ('strDrinkThumb', models.URLField()),
                ('strIngredient1', models.CharField(max_length=255)),
                ('strIngredient2', models.CharField(max_length=255)),
                ('strIngredient3', models.CharField(max_length=255)),
                ('strIngredient4', models.CharField(max_length=255)),
                ('strIngredient5', models.CharField(max_length=255)),
                ('strIngredient6', models.CharField(max_length=255)),
                ('strIngredient7', models.CharField(max_length=255)),
                ('strIngredient8', models.CharField(max_length=255)),
                ('strIngredient9', models.CharField(max_length=255)),
                ('strIngredient10', models.CharField(max_length=255)),
                ('strIngredient11', models.CharField(max_length=255)),
                ('strIngredient12', models.CharField(max_length=255)),
                ('strIngredient13', models.CharField(max_length=255)),
                ('strIngredient14', models.CharField(max_length=255)),
                ('strIngredient15', models.CharField(max_length=255)),
                ('strMeasure1', models.CharField(max_length=255)),
                ('strMeasure2', models.CharField(max_length=255)),
                ('strMeasure3', models.CharField(max_length=255)),
                ('strMeasure4', models.CharField(max_length=255)),
                ('strMeasure5', models.CharField(max_length=255)),
                ('strMeasure6', models.CharField(max_length=255)),
                ('strMeasure7', models.CharField(max_length=255)),
                ('strMeasure8', models.CharField(max_length=255)),
                ('strMeasure9', models.CharField(max_length=255)),
                ('strMeasure10', models.CharField(max_length=255)),
                ('strMeasure11', models.CharField(max_length=255)),
                ('strMeasure12', models.CharField(max_length=255)),
                ('strMeasure13', models.CharField(max_length=255)),
                ('strMeasure14', models.CharField(max_length=255)),
                ('strMeasure15', models.CharField(max_length=255)),
                ('strImageSource', models.CharField(max_length=255)),
                ('strImageAttribution', models.CharField(max_length=255)),
                ('strCreativeCommonsConfirmed', models.CharField(max_length=255)),
                ('dateModified', models.DateField()),
            ],
        ),
    ]
