from django.db import models


class Cocktail(models.Model):
    idDrink = models.CharField(max_length=255,null=True, blank=True)
    strDrink = models.CharField(max_length=255,null=True, blank=True)
    strDrinkAlternate = models.CharField(max_length=255,null=True, blank=True)
    strTags = models.CharField(max_length=255,null=True, blank=True)
    strVideo = models.CharField(max_length=255,null=True, blank=True)
    strIBA = models.CharField(max_length=255,null=True, blank=True)
    strAlcoholic = models.CharField(max_length=255,null=True, blank=True)
    strGlass = models.CharField(max_length=255,null=True, blank=True)
    strInstructions = models.TextField(null=True, blank=True)
    strInstructionsES =models.TextField(null=True, blank=True)
    strInstructionsDE = models.TextField(null=True, blank=True)
    strInstructionsFR = models.TextField(null=True, blank=True)
    strInstructionsIT = models.TextField(null=True, blank=True)
    strInstructionsZH_HANS = models.TextField(null=True, blank=True)
    strInstructionsZH_HANT = models.TextField(null=True, blank=True)
    strDrinkThumb = models.URLField(null=True, blank=True)
    strIngredient1 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient2 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient3 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient4 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient5 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient6 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient7 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient8 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient9 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient10 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient11 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient12 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient13 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient14 = models.CharField(max_length=255,null=True, blank=True)
    strIngredient15 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure1 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure2 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure3 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure4 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure5 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure6 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure7 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure8 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure9 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure10 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure11 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure12 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure13 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure14 = models.CharField(max_length=255,null=True, blank=True)
    strMeasure15 = models.CharField(max_length=255,null=True, blank=True)
    strImageSource = models.CharField(max_length=255,null=True, blank=True)
    strImageAttribution = models.CharField(max_length=255,null=True, blank=True)
    strCreativeCommonsConfirmed = models.CharField(max_length=255,null=True, blank=True)
    dateModified = models.DateTimeField(null=True, blank=True)

